import { Coin, CoinAmino, CoinSDKType } from "../../cosmos/base/v1beta1/coin";
import { Status } from "../common/status";
export interface DemandOrder {
  /**
   * id is a hash of the form generated by GetRollappPacketKey,
   * e.g status/rollappid/packetProofHeight/packetDestinationChannel-PacketSequence which gurantees uniqueness
   */
  id: string;
  /**
   * tracking_packet_key is the key of the packet that is being tracked.
   * This key can change depends on the packet status.
   */
  trackingPacketKey: string;
  price: Coin[];
  fee: Coin[];
  recipient: string;
  isFullfilled: boolean;
  trackingPacketStatus: Status;
}
export interface DemandOrderProtoMsg {
  typeUrl: "/dymensionxyz.dymension.eibc.DemandOrder";
  value: Uint8Array;
}
export interface DemandOrderAmino {
  /**
   * id is a hash of the form generated by GetRollappPacketKey,
   * e.g status/rollappid/packetProofHeight/packetDestinationChannel-PacketSequence which gurantees uniqueness
   */
  id: string;
  /**
   * tracking_packet_key is the key of the packet that is being tracked.
   * This key can change depends on the packet status.
   */
  tracking_packet_key: string;
  price: CoinAmino[];
  fee: CoinAmino[];
  recipient: string;
  is_fullfilled: boolean;
  tracking_packet_status: Status;
}
export interface DemandOrderAminoMsg {
  type: "/dymensionxyz.dymension.eibc.DemandOrder";
  value: DemandOrderAmino;
}
export interface DemandOrderSDKType {
  id: string;
  tracking_packet_key: string;
  price: CoinSDKType[];
  fee: CoinSDKType[];
  recipient: string;
  is_fullfilled: boolean;
  tracking_packet_status: Status;
}